language: cpp
compiler:
  - gcc
  - g++
  - clang++
sudo: false
addons:
  apt:
    packages:
    - valgrind
script:
   - date
   - ls -al
   - make test CXX=g++-4.8 VARS=-DDEBUG
   - ls -al
   - make clean
   - make test CXX=clang++ VARS=-DDEBUG
   - ls -al
   - date
