sudo: required
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - valgrind
script:
   - date
   - ls -al
   - make test VARS=-DDEBUG
   - ls -al
   - make clean
   - make test CXX=clang++ VARS=-DDEBUG
   - ls -al
   - date
